127.0.0.1 - - [08/Sep/2025 15:08:58] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Sep/2025 15:08:58] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [08/Sep/2025 15:14:02] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Sep/2025 15:16:38] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 40904)
Traceback (most recent call last):
  File "/usr/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/usr/lib/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "/home/a/static-rooster/bin/sr_ingest_server.py", line 23, in do_GET
    self.wfile.write(PAGE.replace(b"{msg}", b"ready"))
  File "/usr/lib/python3.10/socketserver.py", line 826, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
127.0.0.1 - - [08/Sep/2025 15:16:38] "GET /favicon.ico HTTP/1.1" 200 -
